###
POST http://127.0.0.1:5000/student/register
Content-Type: application/json

{
  "name": "Rahul",
  "email": "rahul@gmail.com",
  "password": "1234",
  "branch": "CSE",
  "semester": 6,
  "mentor_email": "mentor@college.com"
}
###
POST http://127.0.0.1:5000/student/login
Content-Type: application/json

{
  "email": "rahul@gmail.com",
  "password": "1234"
}
###
POST http://127.0.0.1:5000/timetable/add
Content-Type: application/json

{
  "student_id": 1,
  "day": "Monday",
  "subject": "Data Structures",
  "start_time": "09:00",
  "end_time": "10:00"
}

###
POST http://127.0.0.1:5000/student/register
Content-Type: application/json

{
  "name": "Tasmiya khanum",
  "email": "tasmiyakhanum274@gmail.com",
  "password": "123456",
  "branch": "CSE",
  "semester": 4,
  "mentor_email": "khanumtasmiya189@gmail.com"
}
###
POST http://127.0.0.1:5000/student/register
Content-Type: application/json

{
  "name": "Rahul Sharma",
  "email": "rahul1@gmail.com",
  "password": "123456",
  "branch": "CSE",
  "semester": 4,
  "mentor_email": "mentor@gmail.com"
}

###

POST http://127.0.0.1:5000/student/register
Content-Type: application/json

{
  "name": "Priya Singh",
  "email": "priya1@gmail.com",
  "password": "123456",
  "branch": "ISE",
  "semester": 3,
  "mentor_email": "mentor@gmail.com"
}

###

POST http://127.0.0.1:5000/student/register
Content-Type: application/json

{
  "name": "Arjun Patel",
  "email": "arjun1@gmail.com",
  "password": "123456",
  "branch": "ECE",
  "semester": 5,
  "mentor_email": "mentor@gmail.com"
}
###
POST http://127.0.0.1:5000/leave/apply
Content-Type: application/json

{
  "student_id": 1,
  "from_date": "2026-05-20",
  "to_date": "2026-05-22",
  "reason": "Medical Leave"
}
